Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"

    config.vm.define "mjameauS" do |control|
        control.vm.hostname = "mjameauS"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provider "virtualbox" do |vbS|
            vbS.memory = 1024
            vbS.cpus = 1
        end
        control.vm.provision "shell", path:"scripts/install_k3s_server.sh"
        control.vm.provision "shell", inline: "echo Bringing machine mjameauS up with virtualbox provider"
    end
end
